#!/usr/bin/env bash
set -euo pipefail

PREFIX="[croq-env-fix]"
FAILED=0

# --------------------------------------------------------------------------- #
#  1. perf_event_paranoid                                                      #
# --------------------------------------------------------------------------- #
fix_perf_paranoid() {
    local current
    current=$(cat /proc/sys/kernel/perf_event_paranoid 2>/dev/null || echo "unknown")

    if [[ "$current" == "unknown" ]]; then
        echo "$PREFIX perf_event_paranoid: cannot read — skipping"
        return 1
    fi

    if (( current <= 2 )); then
        echo "$PREFIX perf_event_paranoid=$current — OK"
        return 0
    fi

    echo "$PREFIX perf_event_paranoid=$current — needs fix (must be <= 2)"

    # Try passwordless first, then with password prompt
    if sudo -n sysctl -w kernel.perf_event_paranoid=2 >/dev/null 2>&1; then
        echo "$PREFIX perf_event_paranoid set to 2 (passwordless sudo)"
    elif sudo sysctl -w kernel.perf_event_paranoid=2 >/dev/null 2>&1; then
        echo "$PREFIX perf_event_paranoid set to 2 (sudo with password)"
    else
        echo "$PREFIX ERROR: failed to set perf_event_paranoid — sudo required"
        return 1
    fi

    # Persist across reboots
    local sysctl_conf="/etc/sysctl.d/99-croq-perf.conf"
    if [[ ! -f "$sysctl_conf" ]]; then
        echo "kernel.perf_event_paranoid = 2" | sudo tee "$sysctl_conf" >/dev/null 2>&1 || true
        echo "$PREFIX installed $sysctl_conf for reboot persistence"
    fi

    # Sudoers drop-in so future agent sessions don't need a password for this
    local sudoers_file="/etc/sudoers.d/croq-perf"
    if [[ ! -f "$sudoers_file" ]]; then
        local user
        user=$(whoami)
        echo "$user ALL=(root) NOPASSWD: /usr/sbin/sysctl -w kernel.perf_event_paranoid=*" \
            | sudo tee "$sudoers_file" >/dev/null 2>&1 || true
        sudo chmod 0440 "$sudoers_file" 2>/dev/null || true
        echo "$PREFIX installed $sudoers_file for passwordless future fixes"
    fi

    # Verify
    local verify
    verify=$(cat /proc/sys/kernel/perf_event_paranoid)
    if (( verify <= 2 )); then
        echo "$PREFIX perf_event_paranoid=$verify — FIXED"
        return 0
    else
        echo "$PREFIX ERROR: perf_event_paranoid still $verify after fix attempt"
        return 1
    fi
}

# --------------------------------------------------------------------------- #
#  2. CUDA PATH                                                                #
# --------------------------------------------------------------------------- #
fix_cuda_path() {
    if command -v nvcc >/dev/null 2>&1; then
        local nvcc_path
        nvcc_path=$(command -v nvcc)
        local cuda_home
        cuda_home=$(dirname "$(dirname "$nvcc_path")")
        echo "$PREFIX nvcc found at $nvcc_path — OK"
        echo "$PREFIX CUDA_HOME=$cuda_home"
        export CUDA_HOME="$cuda_home"
        return 0
    fi

    echo "$PREFIX nvcc not on PATH — searching..."

    local best_cuda=""
    local best_version=0

    # Check /usr/local/cuda (symlink) first, then versioned dirs
    for candidate in /usr/local/cuda /usr/local/cuda-*; do
        if [[ -x "$candidate/bin/nvcc" ]]; then
            local ver_str
            ver_str=$(basename "$candidate" | sed 's/cuda-//' | sed 's/cuda/0/')
            # Convert version to comparable number (major * 1000 + minor * 10)
            local major minor ver_num
            major=$(echo "$ver_str" | cut -d. -f1)
            minor=$(echo "$ver_str" | cut -d. -f2 2>/dev/null || echo "0")
            ver_num=$(( major * 1000 + minor * 10 ))
            if (( ver_num > best_version )); then
                best_version=$ver_num
                best_cuda="$candidate"
            fi
        fi
    done

    if [[ -z "$best_cuda" ]]; then
        echo "$PREFIX ERROR: no CUDA installation found under /usr/local/cuda*"
        return 1
    fi

    echo "$PREFIX found CUDA at $best_cuda"
    export CUDA_HOME="$best_cuda"
    export PATH="$best_cuda/bin:$PATH"
    export LD_LIBRARY_PATH="${best_cuda}/lib64:${LD_LIBRARY_PATH:-}"

    # Verify
    if command -v nvcc >/dev/null 2>&1; then
        echo "$PREFIX nvcc=$(nvcc --version 2>&1 | tail -1) — FIXED"

        # Write a profile snippet for persistence across shell sessions
        local profile_file="$HOME/.croq-cuda-env.sh"
        cat > "$profile_file" <<ENVEOF
# Auto-generated by croq-env-fix — CUDA environment
export CUDA_HOME="$best_cuda"
export PATH="$best_cuda/bin:\$PATH"
export LD_LIBRARY_PATH="${best_cuda}/lib64:\${LD_LIBRARY_PATH:-}"
ENVEOF
        echo "$PREFIX wrote $profile_file (source it in .bashrc for persistence)"
        return 0
    else
        echo "$PREFIX ERROR: nvcc still not found after PATH fix"
        return 1
    fi
}

# --------------------------------------------------------------------------- #
#  3. RmProfilingAdminOnly                                                     #
# --------------------------------------------------------------------------- #
fix_nvidia_profiling() {
    local params_file="/proc/driver/nvidia/params"
    if [[ ! -f "$params_file" ]]; then
        echo "$PREFIX nvidia params file not found — skipping (driver may not be loaded)"
        return 0
    fi

    local current
    current=$(grep -o 'RmProfilingAdminOnly: [0-9]*' "$params_file" 2>/dev/null | awk '{print $2}')

    if [[ -z "$current" ]]; then
        echo "$PREFIX RmProfilingAdminOnly not found in params — skipping"
        return 0
    fi

    if (( current == 0 )); then
        echo "$PREFIX RmProfilingAdminOnly=$current — OK"
        return 0
    fi

    echo "$PREFIX RmProfilingAdminOnly=$current — needs fix (must be 0)"

    local modprobe_conf="/etc/modprobe.d/nvidia-profiling.conf"
    if [[ ! -f "$modprobe_conf" ]]; then
        echo "options nvidia NVreg_RestrictProfilingToAdminUsers=0" \
            | sudo tee "$modprobe_conf" >/dev/null 2>&1 || true
        echo "$PREFIX installed $modprobe_conf"
    fi

    echo "$PREFIX NOTE: nvidia module reload required for RmProfilingAdminOnly fix"
    echo "$PREFIX Run manually when safe: sudo rmmod nvidia_uvm nvidia && sudo modprobe nvidia nvidia_uvm"
    echo "$PREFIX Or reboot the machine"
    return 1
}

# --------------------------------------------------------------------------- #
#  4. ncu availability                                                         #
# --------------------------------------------------------------------------- #
fix_ncu() {
    if command -v ncu >/dev/null 2>&1; then
        echo "$PREFIX ncu found at $(command -v ncu) — OK"
        return 0
    fi

    # ncu lives in the CUDA toolkit bin dir
    if [[ -n "${CUDA_HOME:-}" && -x "$CUDA_HOME/bin/ncu" ]]; then
        echo "$PREFIX ncu found at $CUDA_HOME/bin/ncu (already on PATH via CUDA fix) — OK"
        return 0
    fi

    # Search common locations
    for candidate in /usr/local/cuda/bin/ncu /usr/local/cuda-*/bin/ncu /opt/nvidia/nsight-compute/*/ncu; do
        if [[ -x "$candidate" ]]; then
            local ncu_dir
            ncu_dir=$(dirname "$candidate")
            export PATH="$ncu_dir:$PATH"
            echo "$PREFIX ncu found at $candidate — added to PATH — FIXED"
            return 0
        fi
    done

    echo "$PREFIX ERROR: ncu not found anywhere"
    return 1
}

# --------------------------------------------------------------------------- #
#  Main                                                                        #
# --------------------------------------------------------------------------- #
echo "$PREFIX ================================================"
echo "$PREFIX  croq-env-fix: GPU profiling environment fixer"
echo "$PREFIX ================================================"
echo ""

fix_perf_paranoid || FAILED=1
echo ""
fix_cuda_path     || FAILED=1
echo ""
fix_nvidia_profiling || FAILED=1
echo ""
fix_ncu           || FAILED=1
echo ""

if (( FAILED )); then
    echo "$PREFIX ================================================"
    echo "$PREFIX  RESULT: some fixes need manual intervention"
    echo "$PREFIX ================================================"
    exit 1
else
    echo "$PREFIX ================================================"
    echo "$PREFIX  RESULT: all checks passed"
    echo "$PREFIX ================================================"

    # Print sourceable env block
    echo ""
    echo "$PREFIX ENV_BLOCK_START"
    echo "export CUDA_HOME=\"${CUDA_HOME:-/usr/local/cuda}\""
    echo "export PATH=\"${CUDA_HOME:-/usr/local/cuda}/bin:\$PATH\""
    echo "export LD_LIBRARY_PATH=\"${CUDA_HOME:-/usr/local/cuda}/lib64:\${LD_LIBRARY_PATH:-}\""
    echo "$PREFIX ENV_BLOCK_END"
fi

exit 0
